apiVersion: batch/v1
kind: Job
metadata:
  name: fire-and-forget
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: job
        image: basta2022ws.azurecr.io/job:0.0.1
      restartPolicy: Never
